services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./shares:/srv                        
      - ./filebrowser/database.db:/database.db  
      - ./filebrowser/settings.json:/.filebrowser.json
    environment:
      - PUID=1000
      - PGID=1000
